- bagg/index.html
> made this crap page to give BAGG winners a free ticket to the show

- join/index.html
> add join page

- index.html
> add costume contest text

- index.html
> trim past shows in oct block

- virginsofthenight/index.html
> fix virginsofthenight on mobile

- index.html
per @seanthetransgay 's suggestion at the 2019july05 @bawdycaste/social-media  team meeting
> add email link to join

- index.html
> OCT2019: update fallon ticket info

- index.html
did it on the real branch this time
> make the P a span to fix mobile view

- index.html
> fix broken tumblr link

- index.html
> remove past shows

- styles/main.css
Add "word-wrap" property to email element
> fix overflow of email

- index.html
- styles/main.css
refactor and restyle of @jaison2000b's work on #92
> refactor(style): "modernize" lebowski responsiveness

- index.html
Not super happy about the wording, but we need to say something ASAP!!
> feat: add information pointing out our last clay show

- index.html
- styles/main.css
> Temp redesign

- styles/main.css
makes an animated rainbow shadow around .bo class referenced from codpen.io project
> style: add rainbow effect to special text

- index.html
damn you @jaison2000b, your lazy review let this duplicate link go live!
> fix(link): change ticket link for dna show

- index.html
> feat: add times to show dates

- index.html
> fix(time): add 8pm showtime fo dna link

- index.html
- styles/main.css
changes show information to: will return soon!
> feat: Will return soon

- index.html
update the return information with a vague message about shows being postponed for a while.
> feat: add show postponement information

- .vscode/settings.json
- index.html
- styles/main.css
> feat: updated postponement text
